### ISSUE TITLE
Set CardNo ?

### ISSUE THREAD

**Issue by bezhanSalleh** [dnaextrim/php_zklib#35]
could you update the setUser function to set the cardNo also. or how would you go about it... just some pointer would be great on how to do it.

**Comment by dnaextrim** [comment]
Hi. I am sorry that I have not been able to develop this library anymore because i busy with my work, so I do not have time to develop this library yet. I try this month I will try to make a video how do I get a command to attendance machine and how do I create this library. So I hope in the future you can modify this library to work with any firmware version of ZK. The video will be uploaded on my youtube.
Thank you
